# Generated by Django 4.2.3 on 2023-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='documents/')),
                ('number_of_pages', models.IntegerField()),
                ('page_width', models.IntegerField()),
                ('page_height', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('wdith', models.IntegerField()),
                ('height', models.IntegerField()),
                ('number_of_channels', models.IntegerField()),
            ],
        ),
    ]
