# Generated by Django 4.2.3 on 2023-08-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dp_controller', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='wdith',
            new_name='width',
        ),
    ]
