# Generated by Django 4.2.3 on 2023-08-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp_controller', '0004_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
